# Generated by Django 3.0.2 on 2020-01-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_contact_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='start_date',
        ),
    ]
