# Generated by Django 3.0.2 on 2020-01-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_contact_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(default=2, help_text='Provide your gender here', max_length=20),
            preserve_default=False,
        ),
    ]
