# Generated by Django 3.0.2 on 2020-01-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_contact_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(default='Male', help_text='Provide your gender here', max_length=20),
        ),
    ]
