# Generated by Django 3.0.2 on 2020-01-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200122_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='gender',
            new_name='gender1',
        ),
    ]
