# Generated by Django 3.0.2 on 2020-01-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200122_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender1',
            field=models.CharField(help_text='Provide your gender here', max_length=20, null=True),
        ),
    ]
