# Generated by Django 3.0.2 on 2020-01-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200122_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='gender1',
            new_name='new_gender',
        ),
    ]
