# Generated by Django 3.0.2 on 2020-01-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200122_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='new_gender',
        ),
    ]
