# Generated by Django 3.0.2 on 2020-01-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20200130_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='zip',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
